<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Date Difference Calculator</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      padding: 30px;
      max-width: 400px;
      margin: auto;
    }
    input, button {
      margin-top: 10px;
      padding: 10px;
      width: 100%;
    }
    #result {
      margin-top: 20px;
      font-weight: bold;
    }
  </style>
</head>
<body>

  <h2>📅 Days Between Dates</h2>

  <label>Start Date:</label>
  <input type="date" id="startDate" />

  <label>End Date:</label>
  <input type="date" id="endDate" />

  <button onclick="calculateDays()">Calculate Days</button>

  <div id="result"></div>

  <script>
    // Set today's date as default for End Date
    const today = new Date().toISOString().split('T')[0];
    document.getElementById('endDate').value = today;

    function formatDateToDDMMYYYY(dateStr) {
      const [year, month, day] = dateStr.split("-");
      return `${day}/${month}/${year}`;
    }

    function calculateDays() {
      const startInput = document.getElementById('startDate').value;
      const endInput = document.getElementById('endDate').value;

      if (!startInput || !endInput) {
        document.getElementById('result').innerText = "❌ Please select both dates.";
        return;
      }

      const start = new Date(startInput);
      const end = new Date(endInput);
      const diffTime = end - start;
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      const startFormatted = formatDateToDDMMYYYY(startInput);
      const endFormatted = formatDateToDDMMYYYY(endInput);

      document.getElementById('result').innerText =
        `From **${startFormatted}** to **${endFormatted}** 👉 ${diffDays} day(s).`;
    }
  </script>

</body>
</html>
